/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateDeploymentCatalogArgs } from "./CreateDeploymentCatalogArgs";
import { UpdateDeploymentCatalogArgs } from "./UpdateDeploymentCatalogArgs";
import { DeleteDeploymentCatalogArgs } from "./DeleteDeploymentCatalogArgs";
import { DeploymentCatalogFindManyArgs } from "./DeploymentCatalogFindManyArgs";
import { DeploymentCatalogFindUniqueArgs } from "./DeploymentCatalogFindUniqueArgs";
import { DeploymentCatalog } from "./DeploymentCatalog";
import { DeploymentCatalogService } from "../deploymentCatalog.service";

@graphql.Resolver(() => DeploymentCatalog)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class DeploymentCatalogResolverBase {
  constructor(
    protected readonly service: DeploymentCatalogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DeploymentCatalog",
    action: "read",
    possession: "any",
  })
  async _deploymentCatalogsMeta(
    @graphql.Args() args: DeploymentCatalogFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [DeploymentCatalog])
  @nestAccessControl.UseRoles({
    resource: "DeploymentCatalog",
    action: "read",
    possession: "any",
  })
  async deploymentCatalogs(
    @graphql.Args() args: DeploymentCatalogFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DeploymentCatalog[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "DeploymentCatalog",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => DeploymentCatalog, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DeploymentCatalog",
    action: "read",
    possession: "own",
  })
  async deploymentCatalog(
    @graphql.Args() args: DeploymentCatalogFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DeploymentCatalog | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "DeploymentCatalog",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => DeploymentCatalog)
  @nestAccessControl.UseRoles({
    resource: "DeploymentCatalog",
    action: "create",
    possession: "any",
  })
  async createDeploymentCatalog(
    @graphql.Args() args: CreateDeploymentCatalogArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DeploymentCatalog> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "DeploymentCatalog",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"DeploymentCatalog"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => DeploymentCatalog)
  @nestAccessControl.UseRoles({
    resource: "DeploymentCatalog",
    action: "update",
    possession: "any",
  })
  async updateDeploymentCatalog(
    @graphql.Args() args: UpdateDeploymentCatalogArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DeploymentCatalog | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "DeploymentCatalog",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"DeploymentCatalog"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DeploymentCatalog)
  @nestAccessControl.UseRoles({
    resource: "DeploymentCatalog",
    action: "delete",
    possession: "any",
  })
  async deleteDeploymentCatalog(
    @graphql.Args() args: DeleteDeploymentCatalogArgs
  ): Promise<DeploymentCatalog | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
