/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestMorgan from "nest-morgan";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DeploymentCatalogService } from "../deploymentCatalog.service";
import { DeploymentCatalogCreateInput } from "./DeploymentCatalogCreateInput";
import { DeploymentCatalogWhereInput } from "./DeploymentCatalogWhereInput";
import { DeploymentCatalogWhereUniqueInput } from "./DeploymentCatalogWhereUniqueInput";
import { DeploymentCatalogFindManyArgs } from "./DeploymentCatalogFindManyArgs";
import { DeploymentCatalogUpdateInput } from "./DeploymentCatalogUpdateInput";
import { DeploymentCatalog } from "./DeploymentCatalog";
@swagger.ApiBasicAuth()
export class DeploymentCatalogControllerBase {
  constructor(
    protected readonly service: DeploymentCatalogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post()
  @nestAccessControl.UseRoles({
    resource: "DeploymentCatalog",
    action: "create",
    possession: "any",
  })
  @swagger.ApiCreatedResponse({ type: DeploymentCatalog })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: DeploymentCatalogCreateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<DeploymentCatalog> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "DeploymentCatalog",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"DeploymentCatalog"} creation is forbidden for roles: ${roles}`
      );
    }
    return await this.service.create({
      data: data,
      select: {
        appVersion: true,
        artifactId: true,
        configVersion: true,
        createdAt: true,
        dbVersion: true,
        environment: true,
        groupId: true,
        host: true,
        id: true,
        updatedAt: true,
        vaultVersion: true,
      },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get()
  @nestAccessControl.UseRoles({
    resource: "DeploymentCatalog",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: [DeploymentCatalog] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(DeploymentCatalogFindManyArgs)
  async findMany(
    @common.Req() request: Request,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<DeploymentCatalog[]> {
    const args = plainToClass(DeploymentCatalogFindManyArgs, request.query);

    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "DeploymentCatalog",
    });
    const results = await this.service.findMany({
      ...args,
      select: {
        appVersion: true,
        artifactId: true,
        configVersion: true,
        createdAt: true,
        dbVersion: true,
        environment: true,
        groupId: true,
        host: true,
        id: true,
        updatedAt: true,
        vaultVersion: true,
      },
    });
    return results.map((result) => permission.filter(result));
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id")
  @nestAccessControl.UseRoles({
    resource: "DeploymentCatalog",
    action: "read",
    possession: "own",
  })
  @swagger.ApiOkResponse({ type: DeploymentCatalog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: DeploymentCatalogWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<DeploymentCatalog | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "DeploymentCatalog",
    });
    const result = await this.service.findOne({
      where: params,
      select: {
        appVersion: true,
        artifactId: true,
        configVersion: true,
        createdAt: true,
        dbVersion: true,
        environment: true,
        groupId: true,
        host: true,
        id: true,
        updatedAt: true,
        vaultVersion: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return permission.filter(result);
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id")
  @nestAccessControl.UseRoles({
    resource: "DeploymentCatalog",
    action: "update",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: DeploymentCatalog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: DeploymentCatalogWhereUniqueInput,
    @common.Body()
    data: DeploymentCatalogUpdateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<DeploymentCatalog | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "DeploymentCatalog",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"DeploymentCatalog"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          appVersion: true,
          artifactId: true,
          configVersion: true,
          createdAt: true,
          dbVersion: true,
          environment: true,
          groupId: true,
          host: true,
          id: true,
          updatedAt: true,
          vaultVersion: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id")
  @nestAccessControl.UseRoles({
    resource: "DeploymentCatalog",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: DeploymentCatalog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: DeploymentCatalogWhereUniqueInput
  ): Promise<DeploymentCatalog | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          appVersion: true,
          artifactId: true,
          configVersion: true,
          createdAt: true,
          dbVersion: true,
          environment: true,
          groupId: true,
          host: true,
          id: true,
          updatedAt: true,
          vaultVersion: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
